import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "highlight.js/styles/github.css";
import { Providers } from "./_components/Providers";
import ClientInitWrapper from "./_components/ClientInitWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ClientInitWrapper>{children}</ClientInitWrapper>
        </Providers>
      </body>
    </html>
  );
}
